name: Build and Release

on: push

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Generate release tag
        id: tag
        run: |
          sha=$(git rev-parse --short HEAD)
          timestamp=$(date +%Y%m%d_%H%M%S)
          echo "release_tag=release-${timestamp}-${sha}" >> $GITHUB_OUTPUT
      
      - name: Zip dist folder
        run: |
          cd dist
          zip -r ../dist.zip .
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
          name: Release ${{ steps.tag.outputs.release_tag }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false
